name: Graphviz

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Installation de Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lancement Graphviz
        run: ./Graphviz/run1.sh g1
        working-directory: Graphviz
