name: Graphviz

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Installation de Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lancement Graphviz
        run: cd Graphviz && ./run1.sh g1

      - name: upload du resultat
        uses: actions/upload-artifact@v4
        with:
          name: envoie vers le fichier g1.svg
          path: Graphviz/g1.svg
